---
- name: Transfer and execute a script.
  hosts: all
  remote_user: timykchang
  tasks:
     - name: Transfer the script
       copy: src=build01.tc dest=/home/timykchang mode=0777

     - name: Execute the script
#       command: bash /home/timykchang/build01.tc
#       command: bsub -n 10 -m cmtest-01 /home/timykchang/lsf_cmd.tc
       command: bsub -n 10 -m cmtest-01 ls

