---
- name: Transfer and execute a script.
  hosts: server
  remote_user: timykchang
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=build01.tc dest=/home/timykchang mode=0777

     - name: Execute the script
       command: bash /home/timykchang/build01.tc

